cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

cats/app/models/user.rb
class User < ApplicationRecord
  after_initialize :ensure_session_token
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true, uniqueness: true

  has_many :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Cat

has_many :requests,
primary_key: :id,
foreign_key: :user_id,
class_name: 'CatRentalRequest'

  attr_reader :password

  COMMON_PASSWORDS = ['password']

  def self.find_by_credentials(uname, pword)
    @user = User.find_by(username: uname)
    @user && @user.is_password?(pword) ? @user : nil
  end

  def password=(psw)
    @password = psw
    self.password_digest = BCrypt::Password.create(psw)
  end

  def is_password?(psw)
    BCrypt::Password.new(self.password_digest).is_password?(psw)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

cats/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to cats_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

cats/app/views/users/_form.html.erb
<% if action == :new %>
  <% action_url = users_url %>
  <% method = :post %>
<% elsif action == :login %>
  <% action_url = new_session_url %>
  <% method = :post %>
<% end %>




<form action="<%= action_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="login">Enter Username:</label>
  <input type="text" name="user[username]" id="login">
  <label for="login">Enter Password:</label>
  <input type="password" name="user[password]" id="login">
  <br>
  <input type="submit" value="SUBMIT">

</form>

cats/app/views/users/index.html.erb
<h1>List of all of the users! Your server is running!</h1>

cats/app/views/users/new.html.erb
<h1>Create new user</h1>

<%= render 'form', user: @user, action: :new %>